require: rubocop-rspec

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - 'lib/**/xcodeproj_extensions.rb'
    - 'vendor/bundle/**/*'
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - 'features/steps/**'

Layout/EndAlignment:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: true

Lint/Void:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/HashAlignment:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Layout/ParameterAlignment:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Style/BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Layout/CaseIndentation:
  Enabled: true

Style/ClassVars:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerBackticks.
Style/CommandLiteral:
  Exclude:
    - 'features/support/*.rb'

Layout/CommentIndentation:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationWidth:
  Exclude:
    - 'spec/**/*.rb'

Layout/LeadingCommentSpace:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PercentQLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RedundantBegin:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideParens:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/RedundantPercentQ:
  Exclude:
    - 'kintsugi.gemspec'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
